spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?severTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234qwer
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true  #user_id 형식을 userId로 매핑하도록 함
  type-aliases-package: com.ryuProject.tripleProject.dto #패키지 경로 줄임
